<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

/**
 * Fixes a schema mismatch introduced when the roles table was added.
 *
 * The original campaign_user migration (2025_09_16) created a 'role' string
 * column. When the roles table was added (2025_12_03) the model and backfill
 * migration were updated to use a 'role_id' FK, but no migration was ever
 * written to actually alter the column on campaign_user. This fixes that.
 *
 * The backfill migration only ran its insert loop if campaigns already existed,
 * so the missing column went undetected until the first campaign was created.
 */
return new class extends Migration
{
    public function up(): void
    {
        // Guard each step with hasColumn() so this migration is safe to re-run
        // after a partial failure (e.g. role_id was added but role wasn't dropped).

        // Step 1 — add role_id FK if it isn't there yet.
        if (! Schema::hasColumn('campaign_user', 'role_id')) {
            Schema::table('campaign_user', function (Blueprint $table) {
                $table->foreignId('role_id')
                      ->nullable()
                      ->after('user_id')
                      ->constrained('roles')
                      ->cascadeOnDelete();
            });
        }

        // Step 2 — backfill role_id from the old string column for any existing rows.
        if (Schema::hasColumn('campaign_user', 'role')) {
            $dmId     = DB::table('roles')->where('name', 'dm')->value('id');
            $playerId = DB::table('roles')->where('name', 'player')->value('id');

            DB::table('campaign_user')->where('role', 'dm')->update(['role_id' => $dmId]);
            DB::table('campaign_user')->where('role', 'player')->update(['role_id' => $playerId]);
        }

        // Step 3 — drop the indexes that reference 'role', then drop the column.
        // SQLite refuses to drop a column while an index still references it.
        // Index names are auto-generated by Laravel from the original migration.
        if (Schema::hasColumn('campaign_user', 'role')) {
            Schema::table('campaign_user', function (Blueprint $table) {
                $table->dropIndex('campaign_user_user_id_role_index');
                $table->dropIndex('campaign_user_campaign_id_role_index');
                $table->dropColumn('role');
            });
        }
    }

    public function down(): void
    {
        Schema::table('campaign_user', function (Blueprint $table) {
            $table->string('role')->nullable()->after('user_id');
        });

        // Restore string values from role_id for any existing rows.
        $roles = DB::table('roles')->pluck('name', 'id');
        foreach (DB::table('campaign_user')->get() as $row) {
            DB::table('campaign_user')
                ->where('id', $row->id)
                ->update(['role' => $roles[$row->role_id] ?? null]);
        }

        Schema::table('campaign_user', function (Blueprint $table) {
            $table->dropForeign(['role_id']);
            $table->dropColumn('role_id');
        });
    }
};
